require_relative './manchester/base'
require_relative './manchester/simple'
require_relative './manchester/complicated'
require_relative './manchester/complex'
require_relative './manchester/complex_plus'
